version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: ./bootstrap.sh
     - run: docker build -t utserver .
     - run: docker run -d -v $(pwd)/data:/data -p 8080:8080 utserver -settingspath /data; sleep 5
     - run: "curl --retry 10 --retry-delay 5 --user admin: http://localhost:8080/gui/"
